# Generated by Django 2.2 on 2020-03-30 20:52

import apps.housing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[apps.housing.models.validateLengthGreaterThanTwo])),
                ('last_name', models.CharField(max_length=20, validators=[apps.housing.models.validateLengthGreaterThanTwo])),
                ('email', models.EmailField(max_length=254, validators=[apps.housing.models.validateLengthGreaterThanTwo])),
                ('message', models.TextField(validators=[apps.housing.models.validateLengthGreaterThanTwo])),
            ],
        ),
    ]
